baseurl = "https://design.oxide.computer"
languageCode = "en-us"
title = "Oxide Computer Company"
canonifyUrls = true

[params]
description = "Bringing the soul back to computing"
github_url = "https://github.com/oxidecomputer"
twitter_handle = "oxidecomputer"
